### ISSUE TITLE
Mismatched new[] / delete in SmiScnData.cpp

### ISSUE THREAD

**Issue by bcdandurand** [coin-or/Smi#1]
int * nColInPrevStages = new int[nstag_];
    nColInPrevStages[0] = 0;
    for (i=1; i<nstag_; i++) {
        nColInPrevStages[i] = nColInPrevStages[i-1] + nColInStage_[i-1];
    }    
    for (i=0; i<integerLength_; i++) {
        int indice = integerIndices[i];
        int stage = colStage_[indice];
        intColsStagewise[stage].push_back(indice - nColInPrevStages[stage]);
    }
delete nColInPrevStages;

******************
Need 
delete [] nColInPrevStages
instead

**Comment by svigerske** [comment]
Fixed in svn repo (rev 655).
