### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by cheesecakeball** [coin-or/Smi#3]
Hi,

I was trying to compile the example in `Sim/examples`. After I enter make, I got following errors:
```
/Documents/DSPtest/test/smi_stable/include/coin/SmiScnData.hpp:12:10: fatal error: 
      'SmiQuadratic.hpp' file not found
#include "SmiQuadratic.hpp"
         ^~~~~~~~~~~~~~~~~~
4 warnings and 1 error generated.
make: *** [stoch.o] Error 1

```
Any idea why this happens? Thanks

**Comment by kingaj12** [comment]
Looks as if include files were reorganized, and not everything is in the test suite.  I'll have a look.  Thanks for letting us know.
